// Generated by CoffeeScript 1.7.1
(function() {
  window.onload = function() {
    var b, r, w;
    w = window.navigator.platform;
    if (w === 'MacIntel') {
      b = 64;
    } else if (w === 'Win32') {
      b = 32;
    } else if (w === 'Win64' && window.navigator.cpuClass === 'x64') {
      b = 64;
    } else if (w === 'Win32' && window.navigator.cpuClass === 'x86') {
      b = 64;
    } else if (w === 'Win32') {
      b = -1;
    } else if (w === 'Linux i686') {
      b = -1;
    } else if (w === 'Linux i686') {
      b = -1;
    } else if (w === 'Linux x86_64') {
      b = 64;
    } else if (w === 'Linux armv7l' || w === 'iPad' || w === 'iPhone') {
      b = 0;
    }
    if (b !== -1) {
      r = "We're having some trouble.  Sorry. :(";
    } else if (b !== 0) {
      r = "Your processor is <div id='bit'>" + b + "</div> bit.";
    } else {
      r = "You're on a phone or a tablet.";
    }
    return document.getElementById('page').innerHTML = "<div class='main'>" + r + "</div> <div class='sub'>Platform: " + window.navigator.platform + ", cpuClass: " + window.navigator.cpuClass + "</div>";
  };

}).call(this);
