// Generated by CoffeeScript 1.7.1
(function() {
  window.ThirtyTwoorSixtyFour = function() {
    var b, w;
    w = window.navigator.platform;
    if (w === 'MacIntel') {
      b = 64;
    }
    if (w === 'Win32') {
      b = 32;
    }
    if (w === 'Win64' && w === 'x64') {
      b = 64;
    }
    if (w === 'Win32' && window.navigator.cpuClass === 'x86') {
      b = 64;
    }
    if (w === 'Win32') {
      b = 64;
    }
    if (w === 'Linux i686') {
      b = 32;
    }
    if (w === 'Linux i686') {
      b = 64;
    }
    if (w === 'Linux x86_64') {
      b = 64;
    }
    if (w === 'Linux armv7l' || w === 'iPad' || w === 'Linux i686' || w === 'iPhone') {
      b = 0;
    }
    if (b !== 0) {
      return "Your processor is <div id='bit'>" + b + "</div> bit.";
    } else {
      return "You're on a phone or a tablet.";
    }
  };

  document.write("<div class='main'>" + (ThirtyTwoorSixtyFour()) + "</div>");

  document.write("<div class='sub'>Platform: " + window.navigator.platform + ", cpuClass: " + window.navigator.cpuClass + "</div>");

}).call(this);
